name: FullStackApp
services:
  db:
    image: bitnami/postgresql:latest
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - ~/.docker/data/postgrs:/var/lib/postgresql/data
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
    networks:  
      - app_network
  redis:
    image: redis:8.4.0-alpine 
    container_name: redis_ceche 
    ports:
      - 6379:6379
    volumes:
      - ~/.docker/data/redis:/redis/data

  backend:
    build: ./backend/ 
    container_name: backend 
    depends_on: 
      - db
      - redis
    networks:
      - app_network
    ports:
      - 5050:${PORT}

networks:
  app_network:
    driver: bridge


